#!/usr/bin/env python3
"""Remove what install.py added. Never deletes user-authored content.

Removes:
    <codex-home>/skills/sol-deepseek-project-orchestrator/
    <codex-home>/agents/deepseek-worker.toml
    <project>/.codex/hooks/<bundled scripts>
    <project>/.codex/hooks.json   (only if it carries the generated marker)

Keeps unless told otherwise:
    <project>/.codex/PROJECT_STATE.md   (pass --purge-state to delete)
    <project>/AGENTS.md                 (always kept; it is user content)

Exit codes: 0 success, 2 usage problem.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SKILL_NAME = "sol-deepseek-project-orchestrator"
AGENT_FILE_NAME = "deepseek-worker.toml"
GENERATED_MARKER = "Generated by sol-deepseek-project-orchestrator"

EXIT_OK = 0
EXIT_ERROR = 2


class UsageError(Exception):
    pass


def parse_args(argv: list[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="uninstall.py",
        description="Remove the orchestrator skill, agent, and project hooks.",
    )
    parser.add_argument("--project", required=True, help="target project root")
    parser.add_argument(
        "--codex-home",
        default=None,
        help="Codex home directory (falls back to the CODEX_HOME variable)",
    )
    parser.add_argument(
        "--purge-state",
        action="store_true",
        help="also delete .codex/PROJECT_STATE.md (destructive; off by default)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="print what would be removed and exit",
    )
    parser.add_argument("--json", action="store_true", help="machine-readable output")
    return parser.parse_args(argv)


def resolve_paths(args: argparse.Namespace) -> tuple[Path, Path]:
    project = Path(args.project).expanduser()
    if not project.is_dir():
        raise UsageError(f"--project is not a directory: {project}")
    project = project.resolve()

    raw = args.codex_home or os.environ.get("CODEX_HOME")
    if not raw:
        raise UsageError(
            "no Codex home given. Pass --codex-home PATH or set CODEX_HOME."
        )
    return project, Path(raw).expanduser()


def remove_path(path: Path, dry_run: bool) -> str:
    if not path.exists():
        return "absent"
    if dry_run:
        return "would-remove"
    try:
        if path.is_dir():
            shutil.rmtree(path)
        else:
            path.unlink()
    except OSError as exc:
        return f"failed: {exc}"
    return "removed"


def remove_file(path: Path, dry_run: bool) -> str:
    if not path.is_file():
        return "absent"
    if dry_run:
        return "would-remove"
    try:
        path.unlink()
    except OSError as exc:
        return f"failed: {exc}"
    return "removed"


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    try:
        project, codex_home = resolve_paths(args)
    except UsageError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return EXIT_ERROR

    results: dict[str, str] = {}
    results["skill"] = remove_path(
        codex_home / "skills" / SKILL_NAME, args.dry_run
    )
    results["agent"] = remove_file(
        codex_home / "agents" / AGENT_FILE_NAME, args.dry_run
    )

    hooks_dir = project / ".codex" / "hooks"
    if hooks_dir.is_dir():
        for script in sorted(hooks_dir.glob("*.py")):
            if script.name in {
                "inject_project_state.py",
                "stop_project_state_check.py",
            }:
                results[f"hook:{script.name}"] = remove_file(script, args.dry_run)
        try:
            next(hooks_dir.iterdir())
        except StopIteration:
            results["hook:dir"] = remove_path(hooks_dir, args.dry_run)
        except OSError:
            pass

    hooks_json = project / ".codex" / "hooks.json"
    if hooks_json.is_file():
        try:
            text = hooks_json.read_text(encoding="utf-8", errors="replace")
        except OSError:
            text = ""
        if GENERATED_MARKER in text:
            results["hooks.json"] = remove_file(hooks_json, args.dry_run)
        else:
            results["hooks.json"] = "kept: not generated by this installer"
    else:
        results["hooks.json"] = "absent"

    state = project / ".codex" / "PROJECT_STATE.md"
    if args.purge_state:
        results["PROJECT_STATE.md"] = remove_file(state, args.dry_run)
    else:
        results["PROJECT_STATE.md"] = "kept (use --purge-state to delete)"
    results["AGENTS.md"] = "kept (user content)"

    if args.json:
        print(json.dumps({"results": results}, indent=2))
    else:
        width = max(len(key) for key in results)
        for key, value in results.items():
            print(f"{key:<{width}}  {value}")
        if args.dry_run:
            print("\nDry run: nothing was removed.")
    if any(str(value).startswith("failed") for value in results.values()):
        return EXIT_ERROR
    return EXIT_OK


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:
        print("interrupted", file=sys.stderr)
        raise SystemExit(EXIT_ERROR)
